[versions]
# libraries
androidxCore = "1.13.0"
androidxLlifecycleRuntimeKtx = "2.7.0"
androidxActivityCompose = "1.9.0"
androidxComposeBom = "2024.04.01"
androidxNavigation = "2.7.7"
androidxHiltNavigationCompose = "1.2.0"
androidxNavigationCommonKtx = "2.7.7"
junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
orgMockitoKotlin = "4.1.0"
androidxEspresso = "3.5.0"
androidxLifecycleViewmodelCompose = "2.7.0"
androidxLifecycleRuntimeCompose = "2.7.0"
composeMaterial = "1.7.0-beta04"
androidxComposeMaterial3 = "1.2.0"
androidxComposeMaterial3Adaptive = "1.0.0-alpha09"
ioCoilKtCompose = "2.6.0"
kotlinxSerializationJson = "1.6.3"
okhttpLogging = "4.12.0"
retrofit = "2.11.0"
androidxDataStore = "1.0.0"
androidxPaging = "3.2.1"
room = "2.6.1"
workManager = "2.9.0"
hiltWorker = "1.2.0"
protobuf = "4.26.1"

# plugins
protobufPlugin = "0.9.4"
androidGradlePlugin = "8.4.0"
jetbrainsKotlin = "1.9.23"

# libraries and plugins
daggerHilt = "2.51.1"
appcompat = "1.6.1"
material = "1.11.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLlifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
androidx-compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "androidxComposeMaterial3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-navigation-common-ktx = { group = "androidx.navigation", name = "navigation-common", version.ref = "androidxNavigationCommonKtx"}
junit = { group = "junit", name = "junit", version.ref = "junit"}
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit"}
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
org-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "orgMockitoKotlin" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodelCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleRuntimeCompose" }
io-coil-kt = { group = "io.coil-kt", name = "coil-compose", version.ref = "ioCoilKtCompose" }
com-google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
com-google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLogging" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson",version.ref = "retrofit" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-paging-runtimne = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidxPaging"}
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging"}
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager"}
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorker" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }

# Plugins defined by this project
architecture-sample-application-compose = { id = "architecture.sample.application.compose", version = "unspecified"  }
architecture-sample-library-compose = { id = "architecture.sample.library.compose", version = "unspecified"  }
architecture-sample-application-base-setting = { id = "architecture.sample.application.base.setting", version = "unspecified"  }
architecture-sample-library-base-setting = { id = "architecture.sample.library.base.setting", version = "unspecified"  }

[bundles]
[metadata]
